# Generated by gallery/generate.py; do not edit.
function productivebees_gallery:clear
fill 159 99 164 173 99 166 minecraft:stone
fill 159 100 164 173 100 164 minecraft:glass
fill 159 100 166 173 100 166 minecraft:glass
fill 159 100 165 159 101 165 minecraft:glass
fill 173 100 165 173 101 165 minecraft:glass
# oak-slab-control: oak slab stock control
setblock 160 100 161 minecraft:oak_slab[type=bottom,waterlogged=false]
# feeder-default-bottom: default smooth-stone feeding slab
setblock 163 100 161 productivebees:feeder[facing=south,type=bottom,waterlogged=false,honeylogged=false]
# feeder-oak-bottom: oak feeding slab bottom
setblock 166 100 161 productivebees:feeder[facing=south,type=bottom,waterlogged=false,honeylogged=false]
data merge block 166 100 161 {baseBlock:"minecraft:oak_slab"}
# feeder-oak-top: oak feeding slab top
setblock 169 100 161 productivebees:feeder[facing=south,type=top,waterlogged=false,honeylogged=false]
data merge block 169 100 161 {baseBlock:"minecraft:oak_slab"}
# feeder-oak-double: oak double feeding slab
setblock 172 100 161 productivebees:feeder[facing=south,type=double,waterlogged=false,honeylogged=false]
data merge block 172 100 161 {baseBlock:"minecraft:oak_slab"}
# honey-source: honey source feeding a bounded trough
setblock 160 100 165 productivebees:honey[level=0]
function productivebees_gallery:verify
