# Generated by gallery/generate.py; do not edit.
execute unless block 160 100 161 minecraft:oak_slab[type=bottom,waterlogged=false] run tellraw @a {"text":"gallery mismatch: oak-slab-control","color":"red"}
execute unless block 163 100 161 productivebees:feeder[facing=south,type=bottom,waterlogged=false,honeylogged=false] run tellraw @a {"text":"gallery mismatch: feeder-default-bottom","color":"red"}
execute unless block 166 100 161 productivebees:feeder[facing=south,type=bottom,waterlogged=false,honeylogged=false] run tellraw @a {"text":"gallery mismatch: feeder-oak-bottom","color":"red"}
execute unless block 169 100 161 productivebees:feeder[facing=south,type=top,waterlogged=false,honeylogged=false] run tellraw @a {"text":"gallery mismatch: feeder-oak-top","color":"red"}
execute unless block 172 100 161 productivebees:feeder[facing=south,type=double,waterlogged=false,honeylogged=false] run tellraw @a {"text":"gallery mismatch: feeder-oak-double","color":"red"}
execute unless block 160 100 165 productivebees:honey[level=0] run tellraw @a {"text":"gallery mismatch: honey-source","color":"red"}
tellraw @a {"text":"Productive Bees review gallery checked","color":"green"}
